FROM registry.access.redhat.com/ubi9/go-toolset:1.19.6-2 as builder

USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION=v3.67.1
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/${PULUMI_VERSION}/pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

RUN make build \
    && curl -LO ${PULUMI_URL} \
    && tar -xzvf pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

FROM registry.access.redhat.com/ubi9-minimal:9.2-484

LABEL MAINTAINER "CRC <devtools-cdk@redhat.com>"

# https://www.pulumi.com/docs/reference/cli/environment-variables/
ENV PULUMI_CONFIG_PASSPHRASE "defaultPassphrase"

COPY --from=builder /workspace/out/crc-cloud /workspace/pulumi/pulumi /usr/local/bin/
COPY requirements.txt ./

USER root

RUN microdnf install -y python3 python3-pip zstd && \
    pip install -r requirements.txt && \
    pulumi plugin install resource command v0.7.2

ENTRYPOINT [ "crc-cloud" ]
