FROM registry.access.redhat.com/ubi9/go-toolset:1.19.10-4@sha256:886d1c92a95d63322f6e5cd4d6dc9b0dc9a7226fd22c82e29ceb8383e3221c43 as builder

USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION=v3.76.0
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/${PULUMI_VERSION}/pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

RUN make build \
    && curl -LO ${PULUMI_URL} \
    && tar -xzvf pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

FROM registry.access.redhat.com/ubi9-minimal:9.2-691@sha256:8bf03cbc3aedde6e949090290c1e336613ac423d3451b7b1bcb704f0cf8fac88

LABEL MAINTAINER "CRC <devtools-cdk@redhat.com>"

# https://www.pulumi.com/docs/reference/cli/environment-variables/
ENV PULUMI_CONFIG_PASSPHRASE "defaultPassphrase"

COPY --from=builder /workspace/out/crc-cloud /workspace/pulumi/pulumi /usr/local/bin/
COPY requirements.txt ./

USER root

# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v0.7.2

# renovate: datasource=github-releases depName=pulumi/pulumi-tls
ARG PULUMI_TLS_VERSION=v4.10.0

# renovate: datasource=github-releases depName=pulumi/pulumi-random
ARG PULUMI_RANDOM_VERSION=v4.13.2

# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v5.42.0

# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v2.1.1

RUN microdnf install -y python3 python3-pip zstd && \
    pip install -r requirements.txt && \
    pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} && \
    pulumi plugin install resource tls ${PULUMI_TLS_VERSION} && \
    pulumi plugin install resource random ${PULUMI_RANDOM_VERSION} && \
    pulumi plugin install resource aws ${PULUMI_AWS_VERSION} && \
    pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION}

ENTRYPOINT [ "crc-cloud" ]
