FROM registry.access.redhat.com/ubi9/go-toolset:1.19.10-14.1696536543@sha256:c53f72b29ef0213e92149931f0e31a631b0fec61a3e1373aa748f1735be83c06 as builder

USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION=v3.87.0
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/${PULUMI_VERSION}/pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

RUN make build \
    && curl -LO ${PULUMI_URL} \
    && tar -xzvf pulumi-${PULUMI_VERSION}-linux-x64.tar.gz

FROM quay.io/centos/centos:stream9@sha256:2e2a9f4f7171ccda195f3935192f1150155daab4da305f8c273e9fe6134fe7fa

LABEL MAINTAINER "CRC <devtools-cdk@redhat.com>"

# https://www.pulumi.com/docs/reference/cli/environment-variables/
ENV PULUMI_CONFIG_PASSPHRASE "defaultPassphrase"

COPY --from=builder /workspace/out/crc-cloud /workspace/pulumi/pulumi /usr/local/bin/
COPY requirements.txt ./

USER root

# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v0.9.1

# renovate: datasource=github-releases depName=pulumi/pulumi-tls
ARG PULUMI_TLS_VERSION=v4.11.0

# renovate: datasource=github-releases depName=pulumi/pulumi-random
ARG PULUMI_RANDOM_VERSION=v4.14.0

# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v6.4.0

# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v2.10.0

RUN dnf install -y python3 python3-pip zstd qemu-img && \
    pip install -r requirements.txt && \
    pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} && \
    pulumi plugin install resource tls ${PULUMI_TLS_VERSION} && \
    pulumi plugin install resource random ${PULUMI_RANDOM_VERSION} && \
    pulumi plugin install resource aws ${PULUMI_AWS_VERSION} && \
    pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION}

ENTRYPOINT [ "crc-cloud" ]
