---
# https://github.com/crc-org/crc-cloud/blob/main/pkg/bundle/setup/clustersetup.sh#L282
- name: Get route to console custom
  ansible.builtin.shell: |
    oc get route console-custom -n openshift-console
  register: _route_console_custom
  until: _route_console_custom is succeeded
  retries: 60
  delay: "{{ retry_delay }}"
  changed_when: false

- name: Get console route
  ansible.builtin.shell: >
    oc get route console-custom
    -n openshift-console
    -o jsonpath='{.spec.host}'
  register: _console_spec_host
  retries: "{{ max_retries }}"
  delay: "{{ retry_delay }}"
  until: _console_spec_host is succeeded
  changed_when: false
