---
# https://github.com/crc-org/crc-cloud/blob/main/pkg/bundle/setup/clustersetup.sh#L185
- name: Create alternative cert
  ansible.builtin.shell: >
    openssl req
    -newkey rsa:2048
    -new -nodes
    -x509
    -days 3650
    -keyout nip.key
    -out nip.crt
    -subj "/CN={{ eip }}.{{ alternative_domain }}"
    -addext "subjectAltName=DNS:apps.{{ eip }}.{{ alternative_domain }},DNS:*.apps.{{ eip }}.{{ alternative_domain }},DNS:api.{{ eip }}.{{ alternative_domain }}"

- name: "Create secret for {{ alternative_domain }}"
  ansible.builtin.command: >
    oc create secret tls nip-secret
    --cert=nip.crt
    --key=nip.key
    -n openshift-config
