---
- name: "Get htpasswd for {{ user.name }}"
  ansible.builtin.shell: |
    podman run --rm --network=none registry.access.redhat.com/ubi10/httpd-24 htpasswd -Bbn "{{ user.name }}" "{{ user.password }}" >> htpasswd.txt
