---
- name: Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: _temp_dir

- name: Create Dockerfile
  ansible.builtin.copy:
    content: |
      FROM quay.io/centos/centos:stream9-minimal
      RUN microdnf --setopt=tsflags=nodocs --setopt=install_weak_deps=0 install -y httpd-tools
      ENTRYPOINT ["htpasswd", "-Bbn"]
    dest: "{{ _temp_dir.path }}/Dockerfile"

- name: Build container image for htpasswd
  ansible.builtin.command: |
    podman build -t localhost/htpasswd:latest -f {{ _temp_dir.path }}/Dockerfile

- name: "Get htpasswd for {{ user.name }}"
  ansible.builtin.shell: |
     podman run --rm -ti localhost/htpasswd:latest {{ user.name }} {{ user.password }} >> htpasswd.txt

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ _temp_dir.path }}"
    state: absent
