---
- name: Create kube directory
  ansible.builtin.file:
    path: .kube
    state: directory
    owner: core
    group: core

- name: Copy kubeconfig to user dir
  ansible.builtin.copy:
    src: /opt/kubeconfig
    dest: .kube/config
    remote_src: true
    owner: core
    group: core
