---
# https://github.com/crc-org/crc-cloud/blob/main/pkg/bundle/setup/clustersetup.sh#L178
- name: Patch pull secret
  ansible.builtin.shell: >
    oc -n openshift-config
    patch secret pull-secret
    --type merge
    --patch '{"data":{".dockerconfigjson": "{{ openshift_pull_secret | replace("'", '"') | b64encode }}" }}'
  when: openshift_pull_secret | length > 0
  changed_when: false
  no_log: true
