---
#  https://github.com/crc-org/crc-cloud/blob/main/pkg/bundle/setup/clustersetup.sh#L229
- name: Ensure htpasswd.txt does not exists
  ansible.builtin.file:
    path: htpasswd.txt
    state: absent

- name: Get htpasswd
  ansible.builtin.include_tasks: get_htpasswd.yaml
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: Cleanup htpasswd.txt file
  ansible.builtin.shell: |
    sed -i '/^\s*$/d' htpasswd.txt

- name: Create secret with generic htpass-secret
  ansible.builtin.shell: >
    oc create secret generic htpass-secret
    --from-file=htpasswd=htpasswd.txt
    -n openshift-config
    --dry-run=client
    -o yaml > /tmp/htpass-secret.yaml

- name: Replace htpass-secret
  ansible.builtin.command: oc replace -f /tmp/htpass-secret.yaml
