name: Run 'make check'
on:

  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        go:
          - '1.20'
    steps:
      - name: Check out repository code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go }}
      - name: Run lint checks
        run: make lint
      - name: Run fmt checks
        run: make fmt
