name: Run 'make check'
on:
  push:
    branches:
      - "main"
      - "bash"
  pull_request: {}
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        go:
          - 1.18
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2
      - name: Set up Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version: ${{ matrix.go }}
      - name: Run lint checks
        run: make lint
      - name: Run fmt checks
        run: make fmt
