name: Run 'make check'
on:

  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        go:
          - 1.19
    steps:
      - name: Check out repository code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Set up Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Run lint checks
        run: make lint
      - name: Run fmt checks
        run: make fmt
