name: Run 'make check'
on:

  pull_request:
    branches: 
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
        go:
          - 1.19
    steps:
      - name: Check out repository code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Set up Go
        uses: actions/setup-go@v4.1.0
        with:
          go-version: ${{ matrix.go }}
      - name: Run lint checks
        run: make lint
      - name: Run fmt checks
        run: make fmt
